# Generated by Django 4.2.27 on 2026-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketitem_delete_market_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=30),
        ),
    ]
