# Generated by Django 4.2.27 on 2026-02-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_marketitem_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
